apiVersion: external-secrets.io/v1beta1
kind: SecretStore # This one can be ClusterSecretStore for a cluster lavel resources 
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # Calling local vault running in same cluster
      path: "postgres"
      version: "v1"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "5bd8060e-d284-807f-5210-09e3687ebb02"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"